1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [17]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, WebDriverException
import time
import pandas as pd

driver = webdriver.Chrome()

url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"

videos_data = []

try:
    driver.get(url)
    
    time.sleep(3)
    
    table = driver.find_element(By.XPATH, '//*[@id="mw-content-text"]/div[1]/table[1]')
    
    rank_counter = 1

    for row in table.find_elements(By.TAG_NAME, 'tr')[1:]: 
        try:
            cells = row.find_elements(By.TAG_NAME, 'td')
            if len(cells) == 5:
                name = cells[0].text.split('[')[0].strip().replace('"', '').strip()
                artist = cells[1].text
                views = cells[2].text
                upload_date = cells[3].text
                views = views.split('[')[0].strip()
                
                videos_data.append({
                    "Rank": rank_counter,
                    "Name": name,
                    "Artist": artist,
                    "Upload Date": upload_date,
                    "Views (Billions)": views
                })
                
                rank_counter += 1
        except NoSuchElementException as e:
            print(f"Element not found: {e}")
        except IndexError as e:
            print(f"Index error: {e}")

except WebDriverException as e:
    print(f"WebDriverException: {e}")

finally:
    driver.quit()

df = pd.DataFrame(videos_data)

df

The chromedriver version (125.0.6422.76) detected in PATH at D:\Softwares\chromedriver-win64\chromedriver-win64\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

,Rank,Name,Artist,Upload Date,Views (Billions)
0,1,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.66
1,2,Despacito,Luis Fonsi,"January 12, 2017",8.47
2,3,Johny Johny Yes Papa,LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.92
3,4,Bath Song,Cocomelon - Nursery Rhymes,"May 2, 2018",6.75
4,5,See You Again,Wiz Khalifa,"April 6, 2015",6.30
5,6,Shape of You,Ed Sheeran,"January 30, 2017",6.28
6,7,Wheels on the Bus,Cocomelon - Nursery Rhymes,"May 24, 2018",6.22
7,8,Phonics Song with Two Words,ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.84
8,9,Uptown Funk,Mark Ronson,"November 19, 2014",5.25
9,10,Gangnam Style,Psy,"July 15, 2012",5.20
10,11,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",5.13
11,12,Dame Tu Cosita,Ultra Records,"April 5, 2018",4.68
12,13,Axel F,Crazy Frog,"June 16, 2009",4.60
13,14,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.60
14,15,Baa Baa Black Sheep,Cocomelon - Nursery Rhymes,"June 25, 2018",4.10
15,16,Lakdi Ki Kathi,Jingle Toons,"June 14, 2018",4.07
16,17,Sugar,Maroon 5,"January 14, 2015",4.06
17,18,Counting Stars,OneRepublic,"May 31, 2013",4.03
18,19,Roar,Katy Perry,"September 5, 2013",4.01
19,20,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.96
20,21,Shree Hanuman Chalisa,T-Series Bhakti Sagar,"May 10, 2011",3.90
21,22,Humpty the train on a fruits ride,Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.84
22,23,Sorry,Justin Bieber,"October 22, 2015",3.82
23,24,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.78
24,25,Perfect,Ed Sheeran,"November 9, 2017",3.75
25,26,Dark Horse,Katy Perry,"February 20, 2014",3.74
26,27,Let Her Go,Passenger,"July 25, 2012",3.68
27,28,Faded,Alan Walker,"December 3, 2015",3.65
28,29,Girls Like You,Maroon 5,"May 31, 2018",3.62
29,30,Lean On,Major Lazer Official,"March 22, 2015",3.62

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [18]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, WebDriverException
import time
import pandas as pd

driver = webdriver.Chrome()

The chromedriver version (125.0.6422.76) detected in PATH at D:\Softwares\chromedriver-win64\chromedriver-win64\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

In [19]:
driver.get('https://www.bcci.tv')

In [21]:
fixtures=driver.find_element(By.XPATH,'/html/body/header/div[3]/div[2]/ul/div[1]/a[2]')

fixtures.click()

In [22]:
upcoming=driver.find_element(By.XPATH,'/html/body/section/div/div/div/div/div/div[2]/div[2]/div[1]/div[2]')

upcoming.click()

In [26]:
men=driver.find_element(By.XPATH,'/html/body/section/div/div/div/div/div/div[2]/div[1]/div[3]/div[2]')

men.click()

In [25]:
more_matches=driver.find_element(By.XPATH,'/html/body/section/div/div/div/div/div/div[2]/div[3]/div[2]/div/button')

more_matches.click()

In [28]:
match_data=[]
match_cards = driver.find_elements(By.XPATH, '//div[@id="match-card"]')

for match_card in match_cards:
    try:
        series = match_card.find_element(By.XPATH, './/h5[@class="match-tournament-name ng-binding"]').text
    except:
        series = '-'

    try:
        place = match_card.find_element(By.XPATH, ".//div[@class='match-venue ng-scope']/span[contains(@class, 'ng-binding') and contains(@class, 'ng-scope')]").text
    except:
        place = '-'

    try:
        date = match_card.find_element(By.XPATH, './/div[@class="match-dates ng-binding"]').text
    except:
        date = '-'

    try:
        time = match_card.find_element(By.XPATH, './/div[@class="match-time no-margin ng-binding"]').text
    except:
        time = '-'                   
    match_data.append({
        "Series": series,
        "Place": place,
        "Date": date,
        "Time": time
                })

df=pd.DataFrame(match_data)

df

,Series,Place,Date,Time
0,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club,",6 Jul,16:30 IST
1,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club,",7 Jul,16:30 IST
2,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club,",10 Jul,16:30 IST
3,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club,",13 Jul,16:30 IST
4,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club,",14 Jul,16:30 IST
5,Bangladesh Tour Of India Test Series 2024,"MA Chidambaram Stadium,",19 Sep,9:30
6,Bangladesh Tour Of India Test Series 2024,"Green Park,",27 Sep,9:30
7,Bangladesh Tour Of India T20 Series 2024,"Himachal Pradesh Cricket Association Stadium,",6 Oct,19:00 IST
8,Bangladesh Tour Of India T20 Series 2024,"Arun Jaitley Stadium,",9 Oct,19:00 IST
9,Bangladesh Tour Of India T20 Series 2024,"Rajiv Gandhi International Stadium,",12 Oct,19:00 IST
10,New Zealand Tour Of India Test Series 2024,"M Chinnaswamy Stadium,",16 Oct,9:30 IST
11,New Zealand Tour Of India Test Series 2024,"Maharashtra Cricket Association Stadium,",24 Oct,9:30 IST
12,New Zealand Tour Of India Test Series 2024,"Wankhede Stadium,",1 Nov,9:30 IST
13,India Tour Of South Africa T20 Series 2024,"Kingsmead,",8 Nov,20:00
14,India Tour Of South Africa T20 Series 2024,"St George's Park,",10 Nov,20:00
15,India Tour Of South Africa T20 Series 2024,"SuperSport Park,",13 Nov,20:00
16,India Tour Of South Africa T20 Series 2024,"The Wanderers Stadium,",16 Nov,20:00
17,England Tour Of India T20 Series 2025,"MA Chidambaram Stadium,",22 Jan,19:00 IST
18,England Tour Of India T20 Series 2025,"Eden Gardens,",25 Jan,19:00 IST
19,England Tour Of India T20 Series 2025,"Niranjan Shah Stadium,",28 Jan,19:00 IST
20,England Tour Of India T20 Series 2025,"Maharashtra Cricket Association Stadium,",31 Jan,19:00 IST
21,England Tour Of India T20 Series 2025,"Wankhede Stadium,",2 Feb,19:00 IST
22,England Tour Of India ODI Series 2025,"Vidarbha Cricket Association Stadium,",6 Feb,13:30
23,England Tour Of India ODI Series 2025,"Barabati Stadium,",9 Feb,13:30
24,England Tour Of India ODI Series 2025,"Narendra Modi Stadium,",12 Feb,13:30

3. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [32]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

driver = webdriver.Chrome()

driver.get("https://statisticstimes.com/economy/india/indian-states-gdp.php") 

rows = driver.find_elements(By.XPATH, "//table[@id='table_id']/tbody/tr")

rank = []
state = []
gsdp_18_19 = []
gsdp_19_20 = []
share_18_19 = []
gdp_billion = []

for row in rows:
    cells = row.find_elements(By.TAG_NAME, "td")
    
    if len(cells) > 1:
        rank.append(cells[0].text)
        state.append(cells[1].text)
        gsdp_18_19.append(cells[2].text)
        gsdp_19_20.append(cells[3].text)
        share_18_19.append(cells[5].text)
        gdp_billion.append(cells[6].text)


driver.quit()

data = {
    "Rank": rank,
    "State": state,
    "GSDP(18-19) - at current prices": gsdp_18_19,
    "GSDP(19-20) - at current prices": gsdp_19_20,
    "Share(18-19)": share_18_19,
    "GDP($ billion)": gdp_billion
}

df = pd.DataFrame(data)

print(df)

The chromedriver version (125.0.6422.76) detected in PATH at D:\Softwares\chromedriver-win64\chromedriver-win64\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

   Rank                      State GSDP(18-19) - at current prices  \
0     1                Maharashtra                               -
1     2                 Tamil Nadu                       2,700,109
2     3                  Karnataka                       2,500,733
3     4              Uttar Pradesh                       2,547,861
4     5                    Gujarat                               -
5     6                West Bengal                       1,700,939
6     7                  Rajasthan                       1,524,030
7     8             Andhra Pradesh                       1,439,674
8     9                  Telangana                       1,463,960
9    10             Madhya Pradesh                       1,363,327
10   11                     Kerala                               -
11   12                      Delhi                       1,107,746
12   13                    Haryana                       1,095,535
13   14                     Odisha                         832,790
14   15                      Bihar                               -
15   16                     Punjab                         736,423
16   17                      Assam                         565,401
17   18               Chhattisgarh                         505,887
18   19                  Jharkhand                               -
19   20                Uttarakhand                         346,206
20   21            Jammu & Kashmir                         246,465
21   22           Himachal Pradesh                         207,430
22   23                        Goa                               -
23   24                    Tripura                               -
24   25                 Chandigarh                               -
25   26                 Puducherry                               -
26   27                  Meghalaya                          47,381
27   28                     Sikkim                               -
28   29                    Manipur                               -
29   30          Arunachal Pradesh                               -
30   31                   Nagaland                               -
31   32                    Mizoram                               -
32   33  Andaman & Nicobar Islands                               -

   GSDP(19-20) - at current prices Share(18-19) GDP($ billion)
0                                -       13.17%        414.928
1                        2,364,514        8.78%        276.522
2                        2,269,995        8.38%        264.080
3                        2,258,040        8.37%        263.747
4                        2,230,609        8.17%        257.484
5                        1,531,758        5.63%        177.456
6                        1,365,849        5.06%        159.334
7                        1,303,524        4.87%        153.324
8                        1,308,034        4.76%        150.084
9                        1,246,471        4.63%        145.913
10                       1,046,188        3.96%        124.764
11                       1,014,688        3.73%        117.660
12                         984,055        3.68%        116.001
13                         753,177        2.81%         88.497
14                         751,396        2.76%         86.817
15                         676,164        2.62%         82.397
16                         493,167        1.74%         54.930
17                         464,399        1.74%         54.806
18                         393,722        1.52%         47.909
19                         303,781        1.13%         35.664
20                         224,226        0.82%         25.813
21                         191,728        0.73%         22.984
22                          93,672        0.36%         11.250
23                          72,636        0.27%          8.351
24                          54,285        0.20%          6.154
25                          49,643        0.19%          5.849
26                          42,697        0.16%          5.178
27                          42,756        0.16%          5.014
28                               -        0.16%          4.885
29                          39,630        0.15%          4.643
30                          35,643        0.13%          4.144
31                               -        0.12%          3.715
32                               -        0.04%          1.385

4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [36]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

driver = webdriver.Chrome()

driver.get("https://github.com/")

opensource_menu = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[4]/button"))
)
opensource_menu.click()

trending_link = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[4]/div/div[3]/ul/li[2]/a"))
)
trending_link.click()

WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.XPATH, "//article[@class='Box-row']"))
)

repo_titles = []
repo_descriptions = []
contributors_counts = []
languages_used = []

repos = driver.find_elements(By.XPATH, "//article[@class='Box-row']")

for repo in repos:
    title = repo.find_element(By.XPATH, './/a[@class="Link"]').text
    repo_titles.append(title)
    
    try:
        description = repo.find_element(By.XPATH, './/p[@class="col-9 color-fg-muted my-1 pr-4"]').text
    except:
        description = "No description"
    repo_descriptions.append(description)
    
    try:
        contributors = WebDriverWait(driver, 10).until(
        EC.presence_of_all_elements_located((By.XPATH, "//span[@data-view-component='true']//a[@class='d-inline-block']")))

        num_contributors = len(contributors)
    except:
        contributors = "0"
    contributors_counts.append(num_contributors)
    
    try:
        language = repo.find_element(By.XPATH, ".//span[@itemprop='programmingLanguage']").text
    except:
        language = "No language specified"
    languages_used.append(language)

driver.quit()

data = {
    "Repository Title": repo_titles,
    "Repository Description": repo_descriptions,
    "Contributors Count": contributors_counts,
    "Language Used": languages_used
}

df = pd.DataFrame(data)

print(df)

The chromedriver version (125.0.6422.76) detected in PATH at D:\Softwares\chromedriver-win64\chromedriver-win64\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

                           Repository Title  \
0                   goldmansachs / gs-quant
1                           WerWolv / ImHex
2   microsoft / generative-ai-for-beginners
3               microsoft / semantic-kernel
4                           neovim / neovim
5                       starship / starship
6              Asabeneh / 30-Days-Of-Python
7                             YaLTeR / niri
8                            astral-sh / uv
9                           yt-dlp / yt-dlp
10            pedroslopez / whatsapp-web.js
11                      overleaf / overleaf
12              VinciGit00 / Scrapegraph-ai
13                tigerbeetle / tigerbeetle
14                EricLBuehler / mistral.rs
15                  danielmiessler / fabric
16                    cuixueshe / earthworm
17                     XingangPan / DragGAN
18                     hajimehoshi / ebiten

                               Repository Description  Contributors Count  \
0             Python toolkit for quantitative finance                  95
1   🔍 A Hex Editor for Reverse Engineers, Programm...                  95
2   18 Lessons, Get Started Building with Generati...                  95
3   Integrate cutting-edge LLM technology quickly ...                  95
4     Vim-fork focused on extensibility and usability                  95
5   ☄🌌️ The minimal, blazing-fast, and infinitely ...                  95
6   30 days of Python programming challenge is a s...                  95
7             A scrollable-tiling Wayland compositor.                  95
8   An extremely fast Python package installer and...                  95
9   A feature-rich command-line audio/video downlo...                  95
10  A WhatsApp client library for NodeJS that conn...                  95
11             A web-based collaborative LaTeX editor                  95
12                         Python scraper based on AI                  95
13  The distributed financial transactions databas...                  95
14                      Blazingly fast LLM inference.                  95
15  fabric is an open-source framework for augment...                  95
16  Learning English through the method of constru...                  95
17          Official Code for DragGAN (SIGGRAPH 2023)                  95
18   Ebitengine - A dead simple 2D game engine for Go                  95

       Language Used
0   Jupyter Notebook
1                C++
2   Jupyter Notebook
3                 C#
4         Vim Script
5               Rust
6             Python
7               Rust
8               Rust
9             Python
10        JavaScript
11        JavaScript
12            Python
13               Zig
14              Rust
15            Python
16        TypeScript
17            Python
18                Go

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the
following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
 Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [28]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

driver = webdriver.Chrome()

url = "https://www.billboard.com/"

driver.get(url)

charts=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')

charts.click()

top100=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]/span/a')

top100.click()

ranks=[]
song_names = []
artist_names = []
last_week_ranks = []
peak_ranks = []
weeks_on_board = []

chart_rows = driver.find_elements(By.XPATH, './/div[@class="o-chart-results-list-row-container"]')

for row in chart_rows:
    song_name = row.find_element(By.XPATH, './/h3[@id="title-of-a-story"]').text
    artist_name = row.find_element(By.XPATH, './/li[@class="lrv-u-width-100p"]/ul/li[1]/span[1]').text
    last_week_rank = row.find_element(By.XPATH, './/li[@class="lrv-u-width-100p"]/ul/li[4]/span').text
    peak_rank = row.find_element(By.XPATH, './/li[@class="lrv-u-width-100p"]/ul/li[5]/span').text
    weeks_on_chart = row.find_element(By.XPATH, './/li[@class="lrv-u-width-100p"]/ul/li[6]/span').text

    song_names.append(song_name)
    artist_names.append(artist_name)
    last_week_ranks.append(last_week_rank)
    peak_ranks.append(peak_rank)
    weeks_on_board.append(weeks_on_chart)

df = pd.DataFrame({
    "Song Name": song_names,
    "Artist Name": artist_names,
    "Last Week Rank": last_week_ranks,
    "Peak Rank": peak_ranks,
    "Weeks on Board": weeks_on_board
})

print(df)

driver.quit()

The chromedriver version (125.0.6422.76) detected in PATH at D:\Softwares\chromedriver-win64\chromedriver-win64\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

                 Song Name                                        Artist Name  \
0     Please Please Please                                  Sabrina Carpenter
1          I Had Some Help                Post Malone Featuring Morgan Wallen
2       A Bar Song (Tipsy)                                          Shaboozey
3                 Espresso                                  Sabrina Carpenter
4      Million Dollar Baby                                      Tommy Richman
..                     ...                                                ...
95  Spin You Around (1/24)                                      Morgan Wallen
96          Get In With Me                                       BossMan DLow
97              Kryptonite                                        Don Toliver
98                Carnival  ¥$: Ye & Ty Dolla $ign Featuring Rich The Kid ...
99               Chevrolet                  Dustin Lynch Featuring Jelly Roll

   Last Week Rank Peak Rank Weeks on Board
0               2         1              2
1               1         1              6
2               4         3             10
3               3         3             10
4               5         2              8
..            ...       ...            ...
95             95        24             20
96             88        49             20
97              -        98              1
98             82         1             19
99              -       100              1

[100 rows x 5 columns]

In [29]:
df

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks on Board
0,Please Please Please,Sabrina Carpenter,2,1,2
1,I Had Some Help,Post Malone Featuring Morgan Wallen,1,1,6
2,A Bar Song (Tipsy),Shaboozey,4,3,10
3,Espresso,Sabrina Carpenter,3,3,10
4,Million Dollar Baby,Tommy Richman,5,2,8
...,...,...,...,...,...
95,Spin You Around (1/24),Morgan Wallen,95,24,20
96,Get In With Me,BossMan DLow,88,49,20
97,Kryptonite,Don Toliver,-,98,1
98,Carnival,¥$: Ye & Ty Dolla $ign Featuring Rich The Kid ...,82,1,19
99,Chevrolet,Dustin Lynch Featuring Jelly Roll,-,100,1

6. Scrape the details of Highest selling novels.
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre
Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [32]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException

url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver = webdriver.Chrome()

try:
    driver.get(url)
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, "//table[@class='in-article sortable']")))

    rows = driver.find_elements(By.XPATH, "//table[@class='in-article sortable']/tbody/tr")
    ranks=[]
    book_names = []
    author_names = []
    volumes_sold = []
    publishers = []
    genres = []

    for row in rows:
        try:
            columns = row.find_elements(By.XPATH, "./td")
            if len(columns) >= 5:
                rank=columns[0].text.strip()
                book_name = columns[1].text.strip()
                author_name = columns[2].text.strip()
                volume = columns[3].text.strip()
                publisher = columns[4].text.strip()
                genre = columns[5].text.strip()
                
                ranks.append(rank)
                book_names.append(book_name)
                author_names.append(author_name)
                volumes_sold.append(volume)
                publishers.append(publisher)
                genres.append(genre)
        
        except NoSuchElementException as e:
            print(f"Element not found: {e}")
        
        except Exception as e:
            print(f"An error occurred: {e}")

    df = pd.DataFrame({
        'Rank':ranks,
        'Book Name': book_names,
        'Author Name': author_names,
        'Volumes Sold': volumes_sold,
        'Publisher': publishers,
        'Genre': genres
    })

    print(df)

except TimeoutException:
    print("Timeout occurred waiting for the table to load.")

except Exception as e:
    print(f"Unexpected error: {e}")

finally:
    driver.quit()

The chromedriver version (125.0.6422.76) detected in PATH at D:\Softwares\chromedriver-win64\chromedriver-win64\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

   Rank                                          Book Name       Author Name  \
0     1                                  Da Vinci Code,The        Brown, Dan
1     2               Harry Potter and the Deathly Hallows     Rowling, J.K.
2     3           Harry Potter and the Philosopher's Stone     Rowling, J.K.
3     4          Harry Potter and the Order of the Phoenix     Rowling, J.K.
4     5                               Fifty Shades of Grey      James, E. L.
..  ...                                                ...               ...
95   96                                          Ghost,The    Harris, Robert
96   97                     Happy Days with the Naked Chef     Oliver, Jamie
97   98              Hunger Games,The:Hunger Games Trilogy  Collins, Suzanne
98   99  Lost Boy,The:A Foster Child's Search for the L...      Pelzer, Dave
99  100  Jamie's Ministry of Food:Anyone Can Learn to C...     Oliver, Jamie

   Volumes Sold        Publisher                        Genre
0     5,094,805       Transworld  Crime, Thriller & Adventure
1     4,475,152       Bloomsbury           Children's Fiction
2     4,200,654       Bloomsbury           Children's Fiction
3     4,179,479       Bloomsbury           Children's Fiction
4     3,758,936     Random House              Romance & Sagas
..          ...              ...                          ...
95      807,311     Random House   General & Literary Fiction
96      794,201          Penguin        Food & Drink: General
97      792,187  Scholastic Ltd.          Young Adult Fiction
98      791,507            Orion           Biography: General
99      791,095          Penguin        Food & Drink: General

[100 rows x 6 columns]

In [33]:
df

,Rank,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

7. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import re

def extract_rating(rating_str):
    match = re.search(r'([^\(\)]+)', rating_str)
    if match:
        return match.group(1).strip()
    return None

driver = webdriver.Chrome()

url = "https://www.imdb.com/chart/tvmeter/?ref_=nv_tvv_mptv"
driver.get(url)

WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, ".ipc-metadata-list-summary-item"))
)

series_names = []
year_spans = []
genres = []
runtimes = []
ratings = []
votes = []

series_elements = driver.find_elements(By.XPATH, './/li[@class="ipc-metadata-list-summary-item sc-10233bc-0 iherUv cli-parent"]')

for series in series_elements:
    series_name = None
    year_span = None
    genre = None
    runtime = None
    rating_a = None
    votes_count = None

    try:
        series_name_element = series.find_element(By.XPATH, './/div[@class="ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-b189961a-9 iALATN cli-title"]/a')
        series_name = series_name_element.text.strip() if series_name_element else None

        year_span_element = series.find_element(By.XPATH, './/div[@class="sc-b189961a-7 feoqjK cli-title-metadata"]/span[1]')
        year_span = year_span_element.text.strip() if year_span_element else None

        genre_element = series.find_element(By.XPATH, './/div[@class="sc-b189961a-0 hBZnfJ cli-children"]/div[@class="sc-b189961a-7 feoqjK cli-title-metadata"]/span[3]')
        genre = genre_element.text.strip() if genre_element else None

        runtime_element = series.find_element(By.XPATH, './/div[@class="sc-b189961a-7 feoqjK cli-title-metadata"]/span[2]')
        runtime = runtime_element.text.strip() if runtime_element else None

        rating_element = series.find_element(By.XPATH, './/div[@class="sc-e2dbc1a3-0 ajrIH sc-b189961a-2 fkPBP cli-ratings-container"]/span')
        rating = rating_element.text.strip() if rating_element else None
        rating_a = extract_rating(rating) if rating else None

        votes_count_element = series.find_element(By.XPATH, './/span[@class="ipc-rating-star--voteCount"]')
        votes_count = votes_count_element.text.strip().replace("(", "").replace(")", "") if votes_count_element else None

    except Exception as e:
        print(f"Error extracting series data: {str(e)}")

    series_names.append(series_name)
    year_spans.append(year_span)
    genres.append(genre)
    runtimes.append(runtime)
    ratings.append(rating_a)
    votes.append(votes_count)

driver.quit()

data = {
    "Name": series_names,
    "Year Span": year_spans,
    "Genre": genres,
    "Run Time": runtimes,
    "Rating": ratings,
    "Votes": votes
}

df = pd.DataFrame(data)

In [63]:
df

                    Name  Year Span  Genre Run Time Rating Votes
0               The Boys      2019–  TV-MA   33 eps    8.7  680K
1    House of the Dragon      2022–  TV-MA   20 eps    8.4  398K
2               The Bear      2022–  TV-MA   29 eps    8.6  223K
3            The Acolyte      2024–  TV-14    8 eps    3.4   76K
4             Bridgerton      2020–  TV-MA   25 eps    7.4  186K
..                   ...        ...    ...      ...    ...   ...
95           The X-Files  1993–2018  TV-14  217 eps    8.6  252K
96  Power Book II: Ghost  2020–2024  TV-MA   36 eps    7.5   12K
97            Tulsa King      2022–  TV-MA   19 eps    8.0   73K
98           Kaiju No. 8      2024–  TV-MA   12 eps    8.4  5.2K
99           The Witcher      2019–  TV-MA   26 eps    8.0  575K

[100 rows x 6 columns]

8. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.
ASSIGNMENT

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import pandas as pd
import time

In [3]:
driver=webdriver.Chrome()

driver.get("https://archive.ics.uci.edu/")

The chromedriver version (125.0.6422.76) detected in PATH at D:\Softwares\chromedriver-win64\chromedriver-win64\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

In [4]:
popular_dataset=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/section[1]/div[2]/a')

popular_dataset.click()

In [18]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

def extract_content(element):
    return element.text.strip() if element else None

def scrape_uci_datasets(url):
    driver = webdriver.Chrome()
    driver.get(url)

    try:
        popular_dataset=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/section[1]/div[2]/a')

        popular_dataset.click()
        dataset_elements = driver.find_elements(By.CSS_SELECTOR, 'div.rounded-box.bg-base-100')

        dataset_details = []
        expand_all=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[1]/div/label[2]')
        expand_all.click()
        for dataset_element in dataset_elements:
            details = {}

            name_elem = dataset_element.find_element(By.CSS_SELECTOR, 'h2.truncate.text-primary a.link-hover.link.text-xl.font-semibold')
            details['Dataset Name'] = extract_content(name_elem)

            desc_elem = dataset_element.find_element(By.CSS_SELECTOR, 'p.truncate')
            details['Description'] = extract_content(desc_elem)

            details_table = dataset_element.find_element(By.CSS_SELECTOR, 'div.my-2.hidden.gap-4.md\:grid.grid-cols-12')
            if details_table:
                rows = details_table.find_elements(By.CSS_SELECTOR, 'div.col-span-3.flex.items-center.gap-2')
                if len(rows) >= 4:
                    details['Task'] = extract_content(rows[0]).replace('Task', '').strip()
                    details['Data Type'] = extract_content(rows[1]).replace('Feature Type', '').strip()
                    details['No of Instances'] = extract_content(rows[2]).replace('150 Instances', '').strip()
                    details['No of Attributes'] = extract_content(rows[3]).replace('4 Features', '').strip()

            dataset_details.append(details)

        return dataset_details

    finally:
        driver.quit()

url = 'https://archive.ics.uci.edu/'

dataset_details = scrape_uci_datasets(url)

df = pd.DataFrame(dataset_details)

print(df)

The chromedriver version (125.0.6422.76) detected in PATH at D:\Softwares\chromedriver-win64\chromedriver-win64\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.127); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

                           Dataset Name  \
0                                  Iris
1                              Dry Bean
2                         Heart Disease
3            Rice (Cammeo and Osmancik)
4                                Raisin
5                                 Adult
6  Breast Cancer Wisconsin (Diagnostic)
7                                  Wine
8                          Wine Quality
9                        Bank Marketing

                                         Description  \
0  A small classic dataset from Fisher, 1936. One...
1  Images of 13,611 grains of 7 different registe...
2  4 databases: Cleveland, Hungary, Switzerland, ...
3  A total of 3810 rice grain's images were taken...
4  Images of the Kecimen and Besni raisin varieti...
5  Predict whether income exceeds $50K/yr based o...
6       Diagnostic Wisconsin Breast Cancer Database.
7  Using chemical analysis to determine the origi...
8  Two datasets are included, related to red and ...
9  The data is related with direct marketing camp...

                         Task     Data Type   No of Instances No of Attributes
0              Classification       Tabular
1              Classification  Multivariate  13.61K Instances      16 Features
2              Classification  Multivariate     303 Instances      13 Features
3              Classification  Multivariate   3.81K Instances       7 Features
4              Classification  Multivariate     900 Instances       8 Features
5              Classification  Multivariate  48.84K Instances                1
6              Classification  Multivariate     569 Instances      30 Features
7              Classification       Tabular     178 Instances      13 Features
8  Classification, Regression  Multivariate    4.9K Instances      12 Features
9              Classification  Multivariate  45.21K Instances      17 Features